package com.ninlgde.ccjson.serialize.error;

public enum DeserializeError {
    ERROR_NO_ERROR,
    ERROR_BAD_NUMBER,
    ERROR_BAD_STRING,
    ERROR_BAD_IDENTIFIER,
    ERROR_BAD_ROOT,
    ERROR_STACK_OVERFLOW,
    ERROR_STACK_UNDERFLOW,
    ERROR_MISMATCH_BRACKET,
    ERROR_UNEXPECTED_CHARACTER,
    ERROR_BREAKING_BAD
}